# Generated by Django 2.2 on 2019-08-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0006_userinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
