# Generated by Django 2.2 on 2019-08-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0007_auto_20190829_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
