# Generated by Django 2.2 on 2019-08-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0008_userinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='blood',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
