# Generated by Django 2.2 on 2019-08-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0009_auto_20190829_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
