# Generated by Django 2.2 on 2019-08-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0010_userinfo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
    ]
