# Generated by Django 2.2 on 2019-08-29 23:08

from django.db import migrations, models
import ru.models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0011_remove_userinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics', validators=[ru.models.validate_image]),
        ),
    ]
