# Generated by Django 2.2 on 2019-09-12 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0014_auto_20190830_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
