# Generated by Django 2.2 on 2019-09-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0015_userinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
