# Generated by Django 2.2 on 2019-09-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0016_userinfo_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
