# Generated by Django 2.2 on 2020-01-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0017_auto_20190914_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
