# Generated by Django 2.2 on 2020-01-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0018_auto_20200113_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='alumni',
            field=models.BooleanField(default=False),
        ),
    ]
