# Generated by Django 2.2 on 2020-01-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0019_userinfo_alumni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='profession',
            new_name='relation',
        ),
    ]
