# Generated by Django 2.2 on 2019-08-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('president', models.CharField(max_length=40)),
                ('ast_president', models.CharField(max_length=40)),
            ],
        ),
    ]
