# Generated by Django 2.2 on 2019-08-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
