# Generated by Django 2.2 on 2020-01-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200126_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='daptara_sompadok',
        ),
    ]
