# Generated by Django 2.2 on 2019-09-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_committee_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
