# Generated by Django 2.2 on 2020-01-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20200126_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='president',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
