# Generated by Django 2.2 on 2020-01-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_resetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dept',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='session',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
