# Generated by Django 2.2 on 2020-01-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20200126_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='appayon_sompadok',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='ast_general_secretary_1',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='ast_general_secretary_2',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='ast_president_1',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='ast_president_2',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='ast_president_3',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='ast_treasurer_1',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='ast_treasurer_2',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='doptor_sompadok',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='general_secretary',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='member_1',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='member_2',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='member_3',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='member_4',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='president',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='prochar_sompadok',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='sikkha_krira_sangskritik_sompadok',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='committee',
            name='treasurer',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
