# Generated by Django 2.2 on 2020-01-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20200126_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='sangothonik_sompadok',
            field=models.CharField(blank=True, default='N/A', max_length=40, null=True),
        ),
    ]
